### ISSUE TITLE
Обновить ReYaml до 1.0; Добавить тесты ссылок и переопределения

### ISSUE THREAD

**Issue by Yobas** [Relicta-Team/ReSDK_A3.vr#494]
В репе ReYaml работает из коробки. Нужно тестами прогнать.
```yml

parent: &defaults
  a: 2
  b: 3

child:
  <<: *defaults
  b: 4

RefSements:
    regionName: &region_ref "Reference as is"
    
BaseConfig: &base_cfg
    emplace_val: 321
TestLoot:
  type: Loot # Все конфиги должны иметь тип
  interface: true # интерфейсы только для заготовки шаблонов
  inherit: BaseLoot # Опциональное наследование конфигурации.
  name: some name # Описательное название конфигурации (опционально)
  
  reference: *region_ref
  sect:
    sec_storage: *base_cfg
    v2: 3
  
  allowmaps: # попадание хотя бы под одну группу разрешает тип
    - regex: "*Map[1-9]" #regex like pattern
    - name: TestMap #exact
    - TestMap
    - typeof: BaseMap #type inheritance check
  #allowgamemodes: # не определенный тип снимает все ограничения
  items:
    Item:
      name: Overriden name {i} # {i} - counter of created items
      prob: 35
      count: [1, 3] #ranged count
    Key:
      prob: 20
      count: 4 #fixed count
```
